In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [12]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [13]:
b.dtype

dtype('int32')

In [14]:
b.shape

(2, 3)

In [15]:
b[1,2]

6

In [16]:
b[:,2]

array([3, 6])

In [17]:
b[1,:]

array([4, 5, 6])

In [22]:
b[0,0:2:1]

array([1, 2])

In [24]:
b[1,1] = 0
print(b)

[[1 2 3]
 [4 0 6]]


In [28]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.full((3,2),99)

array([[99, 99],
       [99, 99],
       [99, 99]])

In [32]:
np.random.rand(4,2)

array([[0.01202485, 0.32476317],
       [0.92879877, 0.1224706 ],
       [0.48760136, 0.0925059 ],
       [0.37725336, 0.75526469]])